# default setting
markdown: kramdown
highlighter: null

# plugins used
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  
# ignore gulp and stuff
exclude: ["node_modules", "gulpfile.js", "package.json", "bower_components", "gulp"]

buildtype: production
url: https://parksounds.se

# jekyll-seo-tag settings
title: Park Sounds 2020 - fredag 4 september Huskvarna Folkets park
description: Park Sounds - en alldeles s√§rskild musikfestival fredag 4 september 2020 i Huskvarna Folkets Park
lang: sv_SE
twitter:
  username: theparksounds
social:
  name: Park Sounds
  links:
    - https://twitter.com/theparksounds/
    - https://instagram.com/theparksounds/
    - https://www.facebook.com/parksoundsfestival/
